ALTER SESSION SET "_Oracle_Script"=TRUE;

CREATE USER DSY2201_S4
IDENTIFIED BY "ActForm.S4_DSY"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION, RESOURCE TO DSY2201_S4;

ALTER USER DSY2201_S4 
DEFAULT ROLE RESOURCE;